# Generated by Django 6.0.3 on 2026-03-16 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'building',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
            options={
                'db_table': 'department',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_number', models.CharField(max_length=50)),
                ('floor', models.IntegerField()),
                ('capacity', models.IntegerField(default=4)),
                ('office_type', models.CharField(choices=[('single', 'Single'), ('shared', 'Shared'), ('lab', 'Lab'), ('conference', 'Conference')], max_length=50)),
                ('building', models.ForeignKey(help_text='The building this office belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='offices', to='api.building')),
            ],
            options={
                'db_table': 'office',
                'ordering': ['building', 'room_number'],
                'unique_together': {('building', 'room_number')},
            },
        ),
        migrations.CreateModel(
            name='ITEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(choices=[('computer', 'Computer'), ('monitor', 'Monitor'), ('printer', 'Printer'), ('phone', 'Phone'), ('projector', 'Projector')], max_length=50)),
                ('serial_number', models.CharField(max_length=255, unique=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('maintenance', 'Maintenance'), ('retired', 'Retired')], default='active', max_length=50)),
                ('office', models.ForeignKey(help_text='The office this equipment is assigned to.', on_delete=django.db.models.deletion.CASCADE, related_name='it_equipment', to='api.office')),
            ],
            options={
                'verbose_name': 'IT Equipment',
                'verbose_name_plural': 'IT Equipment',
                'db_table': 'it_equipment',
                'ordering': ['office', 'asset_type'],
            },
        ),
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('academic_title', models.CharField(blank=True, default='', max_length=100)),
                ('system_role', models.CharField(choices=[('faculty', 'Faculty / Staff'), ('department_admin', 'Department Admin'), ('resource_manager', 'Resource Manager'), ('system_admin', 'System Administrator'), ('it_department', 'IT Department')], default='faculty', max_length=50)),
                ('department', models.ForeignKey(help_text='Department this staff member belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='api.department')),
            ],
            options={
                'verbose_name_plural': 'staff',
                'db_table': 'staff',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='OfficeAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if the person is currently occupying the office.', null=True)),
                ('office', models.ForeignKey(help_text='The office being assigned.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.office')),
                ('staff', models.ForeignKey(help_text='The staff member being assigned to the office.', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='api.staff')),
            ],
            options={
                'db_table': 'office_assignment',
                'ordering': ['-start_date'],
            },
        ),
    ]
