# Generated by Django 6.0.3 on 2026-04-24 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_staff_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
