# Generated by Django 6.0.3 on 2026-04-24 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_staff_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(help_text='Reason for requesting this office.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('office', models.ForeignKey(help_text='The office being requested.', on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='api.office')),
                ('staff', models.ForeignKey(help_text='The staff member requesting the office.', on_delete=django.db.models.deletion.CASCADE, related_name='office_requests', to='api.staff')),
            ],
            options={
                'db_table': 'office_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
