# Generated by Django 6.0.3 on 2026-05-21 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_officerequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itequipment',
            name='asset_type',
            field=models.CharField(choices=[('computer', 'Computer'), ('monitor', 'Monitor'), ('printer', 'Printer'), ('phone', 'Phone'), ('projector', 'Projector'), ('smartboard', 'Smart Board'), ('chair', 'Chair'), ('desk', 'Desk')], max_length=50),
        ),
        migrations.CreateModel(
            name='EquipmentRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.CharField(help_text='Type of asset: computer, monitor, printer, phone, projector, smartboard, chair, desk, etc.', max_length=50)),
                ('category', models.CharField(choices=[('it', 'IT / Technology'), ('furniture', 'Furniture / Fixtures')], default='it', max_length=20)),
                ('quantity', models.IntegerField(default=1)),
                ('reason', models.TextField(help_text='Justification/reason for the request.')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_reason', models.TextField(blank=True, default='', help_text='Mandatory explanation if rejected.')),
                ('serial_number_assigned', models.CharField(blank=True, default='', help_text='Physical serial number assigned during approval (for IT category).', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('office', models.ForeignKey(help_text='The office/classroom where the equipment is requested.', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_requests', to='api.office')),
                ('staff', models.ForeignKey(help_text='The staff member who requested the equipment.', on_delete=django.db.models.deletion.CASCADE, related_name='equipment_requests', to='api.staff')),
            ],
            options={
                'db_table': 'equipment_request',
                'ordering': ['-created_at'],
            },
        ),
    ]
